version: '3'

services:
  db:
    container_name: ywp_db
    build:
      context: .
      dockerfile: ./docker/ywp_db/Dockerfile
    volumes:
      - db_volume:/var/lib/postgresql/data

  test_db:
    container_name: ywp_test_db
    build:
      context: .
      dockerfile: ./docker/ywp_test_db/Dockerfile
    environment:
      - POSTGRES_PASSWORD
    ports:
      - '4005:5432'

  server:
    container_name: ywp_server
    build:
      context: .
      dockerfile: ./docker/ywp_server/Dockerfile
    environment:
      DB_HOST: 'ywp_db'
      DB_PORT: '5432'
      DB_PASS: ''
      ASSETS_PATH: '/assets/'

  frontend:
    container_name: ywp_frontend
    build:
      context: .
      dockerfile: ./docker/ywp_frontend/Dockerfile

  jenkins:
    container_name: ywp_jenkins
    image: jenkinsci/blueocean
    ports:
      - '8080:8080'

  nginx:
    container_name: ywp_nginx
    build:
      context: .
      dockerfile: ./docker/ywp_nginx/Dockerfile
    ports:
      - '80:80'

volumes:
  db_volume:
