version: '2'

services:
  db:
    container_name: ywp_db
    build:
      context: .
      dockerfile: ./docker/ywp_db/Dockerfile
    ports:
      - '5432:5432'

  server:
    container_name: ywp_server
    build:
      context: .
      dockerfile: ./docker/ywp_server/Dockerfile
    links:
      - db
    ports:
      - '3333:3000'

  frontend:
    container_name: ywp_frontend
    build:
      context: .
      dockerfile: ./docker/ywp_frontend/Dockerfile
    ports:
      - '1337:1337'

  jenkins:
    container_name: ywp_jenkins
    image: jenkinsci/blueocean
    ports:
      - '9090:8080'
